// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	"github.com/bxcodec/library/message_brocker"
	_ "github.com/bxcodec/library/message_brocker"

	mock "github.com/stretchr/testify/mock"
)

// MessageBroker is an autogenerated mock type for the MessageBroker type
type MessageBroker struct {
	mock.Mock
}

// Receive provides a mock function with given fields:
func (_m *MessageBroker) Receive() (message_brocker.Event, error) {
	ret := _m.Called()

	var r0 message_brocker.Event
	if rf, ok := ret.Get(0).(func() message_brocker.Event); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(message_brocker.Event)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Send provides a mock function with given fields: content
func (_m *MessageBroker) Send(content string) error {
	ret := _m.Called(content)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
