// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	"github.com/bxcodec/library/message_broker"
	"github.com/stretchr/testify/mock"
)

// MailService is an autogenerated mock type for the MailService type
type MailService struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: event
func (_m *MailService) SendEmail(event message_broker.Event) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(message_broker.Event) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
