// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	message_broker2 "github.com/bxcodec/library/message_broker"
	mock "github.com/stretchr/testify/mock"
)

// MessageBroker is an autogenerated mock type for the MessageBroker type
type MessageBroker struct {
	mock.Mock
}

// Receive provides a mock function with given fields: emailChan
func (_m *MessageBroker) Receive(emailChan chan []byte) error {
	ret := _m.Called(emailChan)

	var r0 error
	if rf, ok := ret.Get(0).(func(chan []byte) error); ok {
		r0 = rf(emailChan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Send provides a mock function with given fields: event
func (_m *MessageBroker) Send(event message_broker2.Event) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(message_broker2.Event) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
